export const projects = [
  {
    title: 'poker_long.title',
    description: 'poker_long.description',
    image:
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745639986/photo_2024-12-19_19-25-52_hl8nsp.jpg',

    gallery: [
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745636897/photo_2024-12-19_20-01-02_cnu9ak.jpg',
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745636910/photo_2025-04-21_20-56-25_nmg3id.jpg',
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745639986/photo_2024-12-19_19-25-52_hl8nsp.jpg',
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745636896/photo_2024-10-21_19-34-24_ez4bot.jpg',
    ],
    technologies: [
      'TypeScript',
      'React',
      'Redux Toolkit',
      'RTK Query',
      'Tailwind CSS',
      'Framer Motion',
      'react-hook-form',
      'Yup',
    ],
    year: 2024,
    role: 'Frontend Developer',
    id: '1',
  },
  {
    title: 'builderpad_long.title',
    description: 'builderpad_long.description',
    image: 'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1746817575/bg-footer_euzafb.jpg',
    gallery: [
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745635844/d-user-roles_m5nj4h.png',
      'https://builderpad.com/wp-content/themes/builderpadtheme/assets/images/sel-document.png',
      'https://builderpad.com/wp-content/themes/builderpadtheme/assets/images/file-cabinet.jpg',
      'https://builderpad.com/wp-content/themes/builderpadtheme/assets/images/view-gantt.png',
      'https://builderpad.com/wp-content/themes/builderpadtheme/assets/images/advanced-search.png',
      'https://builderpad.com/wp-content/themes/builderpadtheme/assets/images/advanced-filters.png',
      'https://builderpad.com/wp-content/themes/builderpadtheme/assets/images/rich-posts.png',
    ],
    technologies: [
      'TypeScript',
      'React.js',
      'MUI (Material UI)',
      'Redux Toolkit',
      'RTK Query',
      'react-hook-form',
      'Yup',
    ],
    year: 2022,
    role: 'Frontend Developer',
    id: '2',
  },
  {
    title: 'lottery_long.title',
    description: 'lottery_long.description',
    image:
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745637871/crypto-lottery-solution-image-4_pocvjh.webp',
    gallery: [
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745637871/crypto-lottery-solution-image-3_zcsudi.webp',
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745637871/crypto-lottery-solution-image-4_pocvjh.webp',
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745637871/crypto-lottery-solution-image-2_g0gq0m.webp',
      'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1745637871/crypto-lottery-solution-image-1_hs95kn.webp',
    ],
    technologies: [
      'TypeScript',
      'Next.js',
      'Redux(toolkit)',
      'Web3.js',
      'Wagmi',
      'Web3Modal',
      'Tailwind CSS',
      'react-hook-form',
      'Yup',
      'Nest.js',
      'MongoDB',
      'Swagger',
      'JWT',
    ],
    year: 2023,
    role: 'Full Stack Developer',
    id: '3',
  },
  {
    title: 'health_long.title',
    description: 'health_long.description',
    image: 'https://res.cloudinary.com/dxfqf6fgv/image/upload/v1746817575/health_czjrdc.jpg',
    gallery: [
      'https://a.storyblok.com/f/120667/1584x1110/c21fb101cc/chatbot-illustration-1.png/m/1800x0/filters:format(webp)',
      'https://cdn.prod.website-files.com/628b58b14c93b92656929a99/650489eeec41b8954b29f953_Conversational%20AI%20for%20healthcare.jpg',
      'https://cdn.prod.website-files.com/628b58b14c93b92656929a99/650066bc9a18fc9e7589ac73_Assistant_PR_PCMAscheduling_956x538%20(1).jpg',
      'https://qtxasset.com/cdn-cgi/image/w=384,h=216,f=auto,fit=crop,g=0.5x0.5/https://qtxasset.com/quartz/qcloud5/media/image/956%20x%20537%20-%20Fierce%20Article%20Primary%20Image.png?VersionId=22oWBdKqnK2I.mnLagO8UAjfyrd8fqrO',
    ],
    technologies: [
      'TypeScript',
      'React',
      'Sass',
      'react-hook-form',
      'Socket.io',
      'MobX',
      'SWR',
      'Zod',
    ],
    year: 2024,
    role: 'Frontend Developer',
    id: '4',
  },
]
